modLoader="javafml"
loaderVersion="[41,)"
license="${mod_license}"
issueTrackerURL="https://github.com/MinecraftForge/MinecraftForge/issues"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
credits="${mod_credits}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/better-furnaces-reforged/"
logoFile="bfr_icon.png"
authors="${mc_version}"
description="${mod_description}"


[[dependencies.betterfurnacesreforged]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version}]"
    ordering="NONE"
    side="BOTH"
[[dependencies.betterfurnacesreforged]]
modId="factory_api"
mandatory=true
versionRange="[${factory_api_version},]"
ordering="NONE"
side="BOTH"
[[dependencies.betterfurnacesreforged]]
modId="architectury"
mandatory=true
versionRange="[${architectury_version},]"
ordering="NONE"
side="BOTH"
[[dependencies.betterfurnacesreforged]]
modId="pmmo"
mandatory=false
versionRange="[1,)"
ordering="NONE"
side="BOTH"
[[dependencies.betterfurnacesreforged]]
   modId="jei"
   mandatory=false
   versionRange="[${jei_version},)"
   ordering="NONE"
   side="BOTH"




