modLoader="javafml"
loaderVersion="[37,)"
license="GNU"

[[mods]]
modId="betterfurnacesreforged"
version="${file.jarVersion}"
displayName="BetterFurnaces Reforged"
credits=" TheFrogMC(Original mod creator) and Qelifern (Iron Furnaces creator)"
displayURL="https://www.curseforge.com/minecraft/mc-mods/better-furnaces-reforged/"
logoFile="logo.png"
authors="Wilyicaro"
description='''
This mod is a little remake of the outdated mod from 1.7.10, Better Furnaces, presenting only the main things used in the original mod
'''

[[dependencies.betterfurnacesreforged]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.betterfurnacesreforged]]
   modId="jei"
   mandatory=false
   versionRange="[8,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.betterfurnacesreforged]]
   modId="ftbguilibrary"
   mandatory=false
   versionRange="[1,)"
   ordering="NONE"
   side="BOTH"




