modLoader="javafml"
loaderVersion="[36,)"
license="GNU"

[[mods]]
modId="ultimatefurnaces_bfr"
version="1.1.1"
displayName="Ultimate Furnaces"
credits=" Wilyicaro"
displayURL="https://www.curseforge.com/minecraft/mc-mods/ultimate-furnaces-bfr/"
logoFile="logo.png"
authors="Wilyicaro"
description='''
An official addon for BetterFurnaces Reforged mod, that add 2 new furnaces and 6 forges
'''

[[dependencies.ultimatefurnaces_bfr]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
    [[dependencies.ultimatefurnaces_bfr]]
        modId="betterfurnacesreforged"
        mandatory=true
        versionRange="[1.4.9,]"
        ordering="NONE"
        side="BOTH"
[[dependencies.ultimatefurnaces_bfr]]
        modId="pmmo"
        mandatory=false
        versionRange="[1.16.5-3,)"
        ordering="NONE"
        side="BOTH"
[[dependencies.ultimatefurnaces_bfr]]
   modId="jei"
   mandatory=false
   versionRange="[7,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.ultimatefurnaces_bfr]]
   modId="ftbguilibrary"
   mandatory=false
   versionRange="[1,)"
   ordering="NONE"
   side="BOTH"





